### ISSUE TITLE
File transfer speed and progress not displayed correctly when using many threads

### ISSUE THREAD

**Issue by JanStreffing** [UNICORE-EU/uftp#14]
I use uftp to parallelize the transfer of large files. When running uftp with more that 6 threads, the transfer-rate and progress is not displayed correctly. Only the six threads that are started last are counted. e.g. the following command:

```
uftp cp --identity $UFTP_KEY -t20 -T 50M -v atm_remapped_6h_10v_6h_2134-2134.nc $UFTP_AUTH_URL//work/ab0246/a270092/downloads/TCO319-DART/1950-CTRL/
```

The progress will hover around 10-20% completion with both the progress and speed statistics jumping around wildly.
```
atm_remapped_6h_10u_6h_2134-2134.nc                  11%  4.6G [ 344.0KB/s | 4.1MB/s | 3.3MB/s | 2.3MB/s | 1.3MB/s | 344.9KB/s ]  11.7MB/
atm_remapped_6h_10u_6h_2134-2134.nc                      10%  4.6G [ 629.4B/s | 6.8MB/s | 5.2MB/s | 3.5MB/s | 1.8MB/s | 620B/s ]  17.3MB/s
atm_remapped_6h_10u_6h_2134-2134.nc                    13%  4.6G [ 2.0MB/s | 1.8MB/s | 1.2MB/s | 738.2KB/s | 82.4KB/s | 2.1MB/s ]  8.0MB/s
...

```
Before finally snapping from about 18% to 100% progress:
```
atm_remapped_6h_10u_6h_2134-2134.nc                     100%  4.6G [ 1.9MB/s | 2.3MB/s | 2.2MB/s | 2.1MB/s | 2.0MB/s | 1.9MB/s ]  12.2MB/s
```
Now the progress is now correct, but the transfer-speed is still wrong. It only took about 45 seconds for the 4.6GB, meaning the real transfer-rate was about 100MB/s. 

I think the ability to benchmark is essential is an essential part of a tool set up for high speed data transfer. Version info:
```

uftp --version
UFTP Client 1.4.4, https://www.unicore.eu
Java HotSpot(TM) 64-Bit Server VM 25.51-b03
OS: Linux 4.4.103-6.38-default

```

**Comment by BerndSchuller** [comment]
hi!

thanks for the feedback.

I tried your parameters (4.6G file, -t 20, -T 50M) with client version 1.4.4, but cannot reproduce this, at least not on the JSC UFTP server.

It appears that the server you are using limits the number of parallel sessions, so only 6 transfer threads will launch? You can ask the server admin to [increase that limit](https://uftp-docs.readthedocs.io/en/latest/admin-docs/uftpd/manual.html#configuration-parameters).

I will check if such a limit messes with the thread progress display, that is very well possible.

Thanks again and best regards,
Bernd

**Comment by JanStreffing** [comment]
Limited number of threads would sort of make sense.  In my case I'm on the DKRZ uftp server. With DKRZ support I managed to speed up the process using multiple --streams, to the point that I'm satisfied. Of course it would still be of interest to find out what happened here. I asked them if threads are limited to 6

**Comment by ocarino** [comment]
Hi Bernd and Jan,

these are the current limits at DKRZ:

```
# Limit on concurrent connections per client
export MAX_CONNECTIONS=8
# Limit on parallel TCP streams per FTP data connection
export MAX_STREAMS=16
```

MAX_CONNECTIONS is related to ftp control connections (says uftp manual), so this should not be related to this issue.
Without further thinking or reading 16 streams seems to be a reasonable limit. I could increase that but on the other hand I would not want that single clients eat up too many of the ports usable by uftp  (we do have a port range of 500 ports right now).

@BerndSchuller How are your settings at JSC?

Cheers, Olaf

**Comment by BerndSchuller** [comment]
hi Olaf @ocarino,

it is exactly this limit that is related to this issue, since the client needs one FTP session/control connection per transfer thread plus a couple more for listing files, etc.

At JSC we currently have a (admittedly crazy high) limit of 320... I think something like 64 is reasonable, since some users will use multiple client machines, multiple sessions PLUS multiple streams trying to get all of the network bandwidth ;)

I'd recommend something like

```
export MAX_CONNECTIONS=64
export MAX_STREAMS=4
```

Best regards,
Bernd.

**Comment by ocarino** [comment]
Hi Bernd,

thanks for enlightening me. I thought that only one control session was necessary for one client (as with usual ftp).

I increased MAX_CONNECTIONS to 64 and lowered MAX_STREAMS, so let's see how this works out.

Thanks, cheers, Olaf

**Comment by JanStreffing** [comment]
That made a drastic difference. Firstly this fixed the graphical error i originally reported, secondly the file transferspeed went from 170 MB/s to a whopping 470 MB/s. (with streams 4 and thread 30)

Compared to the original rsync transfer with 5.5 MB/s that's a speedup of ~85 times. Well worth the little bit of extra effort setting things up :+1: 

Thank you both for you help!
