### ISSUE TITLE
Fix client

### ISSUE THREAD

**Issue by surak** [UNICORE-EU/uftp#7]
The client which is here in unusable with the current documentation. The lib directory with the JARS isn't there, and the java/ directory with the right classes (which probably go to the JARs) need to be found properly.

In any case, documentation is in order. 

Thanks!!!

**Comment by BerndSchuller** [comment]
Not sure what you mean.

You want to build the client from source? See 
https://github.com/UNICORE-EU/uftp/blob/master/uftp-client/README-building.txt

Usually it's simpler to just download a release from SourceForge. 
https://sourceforge.net/projects/unicore/files/Clients/UFTP-Client/

Does this refer to some problem with the client/server installation at JSC? Then the right place would be JSC support. 

I'm closing this issue.

**Comment by surak** [comment]
Obviously not :)

When one clones this repository, the uftp client is not in a working state - different from the zip file on sourceforge, which works.

the problem is that the uftp shell script looks for a lib directory which isn’t there, and then needs to run something. There’s nothing for it to run, as the jar files aren’t there. 

Try like this:

Get a clean machine or container whatever with a Java runtime
Clone this repo
Try to run the uftp client.

**Comment by BerndSchuller** [comment]
yeah, but why do you assume that cloning the repo will give you anything useful?

The uftp client is Java based and built using Apache Maven, so you need to do something like
```
git clone https://github.com/UNICORE-EU/uftp.git
cd uftp/uftp-client
mvn package -DskipTests -Ppackman -Dpackage.type=deb -Ddistribution=Debian
```
to build a .deb package plus the .zip archive.

**Comment by surak** [comment]
Because 

1) it’s literally written on the readme: UFTP client - the standalone "uftp" client application
2) the sub readme gives you the idea that everything is not only self-contained, but actually working
3) it’s 2022. This repo is literally the first thing which appears when you search for it. 

There is NO MENTION WHATSOEVER that 
- this repo won’t work by itself (quite the contrary and it’s misleading)
- how to build it, or 
- how to find a working version. 

I can produce a merge request with a fix on the readme, if you want to. Just let me know.

**Comment by BerndSchuller** [comment]
ah I see the source of the misunderstanding. I'll change it.
Sorry for the confusion.
